### ISSUE TITLE
 ValueError: ['path']

### ISSUE THREAD

**Issue by mlotfi2005** [cyberdelia/flask-mysql#16]
HI, I tried to install flask-mysql in windows 7, but I got this 

Installing collected packages: MySQL-python, flask-mysql
  Running setup.py install for MySQL-python
    Complete output from command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\alotfi\\AppData\\Local\\Temp\\pip-build-nwlewwl5\\MySQL-python\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\alotfi\AppData\Local\Temp\pip-rbf1ujnn-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.4
    copying _mysql_exceptions.py -> build\lib.win-amd64-3.4
    creating build\lib.win-amd64-3.4\MySQLdb
    copying MySQLdb\__init__.py -> build\lib.win-amd64-3.4\MySQLdb
    copying MySQLdb\converters.py -> build\lib.win-amd64-3.4\MySQLdb
    copying MySQLdb\connections.py -> build\lib.win-amd64-3.4\MySQLdb
    copying MySQLdb\cursors.py -> build\lib.win-amd64-3.4\MySQLdb
    copying MySQLdb\release.py -> build\lib.win-amd64-3.4\MySQLdb
    copying MySQLdb\times.py -> build\lib.win-amd64-3.4\MySQLdb
    creating build\lib.win-amd64-3.4\MySQLdb\constants
    copying MySQLdb\constants\__init__.py -> build\lib.win-amd64-3.4\MySQLdb\constants
    copying MySQLdb\constants\CR.py -> build\lib.win-amd64-3.4\MySQLdb\constants
    copying MySQLdb\constants\FIELD_TYPE.py -> build\lib.win-amd64-3.4\MySQLdb\constants
    copying MySQLdb\constants\ER.py -> build\lib.win-amd64-3.4\MySQLdb\constants
    copying MySQLdb\constants\FLAG.py -> build\lib.win-amd64-3.4\MySQLdb\constants
    copying MySQLdb\constants\REFRESH.py -> build\lib.win-amd64-3.4\MySQLdb\constants
    copying MySQLdb\constants\CLIENT.py -> build\lib.win-amd64-3.4\MySQLdb\constants
    running build_ext
    building '_mysql' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\alotfi\AppData\Local\Temp\pip-build-nwlewwl5\MySQL-python\setup.py", line 21, in <module>
        setuptools.setup(**metadata)
      File "C:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python34\lib\distutils\command\install.py", line 539, in run
        self.run_command('build')
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\distutils\command\build.py", line 126, in run
        self.run_command(cmd_name)
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 50, in run
        _build_ext.run(self)
      File "C:\Python34\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Python34\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "C:\Python34\lib\site-packages\setuptools\command\build_ext.py", line 183, in build_extension
        _build_ext.build_extension(self, ext)
      File "C:\Python34\lib\distutils\command\build_ext.py", line 503, in build_extension
        depends=ext.depends)
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Python34\lib\site-packages\setuptools\msvc9_support.py", line 52, in query_vcvarsall
        return unpatched['query_vcvarsall'](version, *args, **kwargs)
      File "C:\Python34\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
        raise ValueError(str(list(result.keys())))
    ValueError: ['path']

    ----------------------------------------
Command "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\alotfi\\AppData\\Local\\Temp\\pip-build-nwlewwl5\\MySQL-python\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\alotfi\AppData\Local\Temp\pip-rbf1ujnn-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\alotfi\AppData\Local\Temp\pip-build-nwlewwl5\MySQL-python

**Comment by cyberdelia** [comment]
Looks like a problem with Mysqldb-python compilation, not related to flask-mysql.

**Comment by mlotfi2005** [comment]
Could you please show me what to do, I am new to python world.
thanks, your help is appreciated.

**Comment by Regner** [comment]
I would suggest doing "pip install mysqldb-python" and trying to track down that error.
